export interface ICar {
    id: string;
    vin: string;
    year: string;
    make: string;
    model: string;
    trimLevel: string;
    mileage: string;
    serviceHistory: string;
    vehicleType: string;
    driveType: string;
    transmissionType: string;
    fuelType: string;
    bodyColor: string;
    ownership: string;
    features: string;
    apartmentNumber: string;
    streetAddress: string;
    city: string;
    state: string;
    country: string;
    minPrice: number;
    images: any;
    status: string;
    userDetail?: any;
    bids?:any[];
    view:number;
    winUserDetail?: any;
    sellerPayment?: any;
    buyerPayment?: any;
    auctionAt: any;
    note?: string;
    description?: string;
    changes?: string;
    bodyColorCode?: string;
    lastBid?:number;
    reserveType?:string;
    asIsWhereIs?:boolean;
    isDrivable?:boolean;
    listedBy?:string;
}
